yas:
  services:
    cart: http://cart.staging.svc.cluster.local/cart
    customer: http://customer.staging.svc.cluster.local/customer
    inventory: http://inventory.staging.svc.cluster.local/inventory
    location: http://location.staging.svc.cluster.local/location
    media: http://media.staging.svc.cluster.local/media
    order: http://order.staging.svc.cluster.local/order
    payment: http://payment.staging.svc.cluster.local/payment
    payment-paypal: http://payment-paypal.staging.svc.cluster.local/payment-paypal
    product: http://product.staging.svc.cluster.local/product
    promotion: http://promotion.staging.svc.cluster.local/promotion
    rating: http://rating.staging.svc.cluster.local/rating
    search: http://search.staging.svc.cluster.local/search
    tax: http://tax.staging.svc.cluster.local/tax
    sampledata: http://sampledata.staging.svc.cluster.local/sampledata
    recommendation: http://recommendation.staging.svc.cluster.local/recommendation
    webhook: http://webhook.staging.svc.cluster.local/webhook
gatewayRoutesConfig:
  spring:
    cloud:
      gateway:
        routes:
        - id: cart_api
          uri: http://cart.staging.svc.cluster.local
          predicates:
          - Path=/api/cart/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: customer_api
          uri: http://customer.staging.svc.cluster.local
          predicates:
          - Path=/api/customer/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: inventory_api
          uri: http://inventory.staging.svc.cluster.local
          predicates:
          - Path=/api/inventory/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: location_api
          uri: http://location.staging.svc.cluster.local
          predicates:
          - Path=/api/location/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: media_api
          uri: http://media.staging.svc.cluster.local
          predicates:
          - Path=/api/media/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
        - id: order_api
          uri: http://order.staging.svc.cluster.local
          predicates:
          - Path=/api/order/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: payment_api
          uri: http://payment.staging.svc.cluster.local
          predicates:
          - Path=/api/payment/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: payment-paypal_api
          uri: http://payment-paypal.staging.svc.cluster.local
          predicates:
          - Path=/api/payment-paypal/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: product_api
          uri: http://product.staging.svc.cluster.local
          predicates:
          - Path=/api/product/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: promotion_api
          uri: http://promotion.staging.svc.cluster.local
          predicates:
          - Path=/api/promotion/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: rating_api
          uri: http://rating.staging.svc.cluster.local
          predicates:
          - Path=/api/rating/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: search_api
          uri: http://search.staging.svc.cluster.local
          predicates:
          - Path=/api/search/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: tax_api
          uri: http://tax.staging.svc.cluster.local
          predicates:
          - Path=/api/tax/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: sampledata_api
          uri: http://sampledata.staging.svc.cluster.local
          predicates:
          - Path=/api/sampledata/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: recommendation_api
          uri: http://recommendation.staging.svc.cluster.local
          predicates:
          - Path=/api/recommendation/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
        - id: webhook_api
          uri: http://webhook.staging.svc.cluster.local
          predicates:
          - Path=/api/webhook/**
          filters:
          - RewritePath=/api/(?<segment>.*), /${segment}
          - TokenRelay=
