ui:
  image:
    tag: latest
  ingress:
    enabled: false
    host: storefront-ui.dev.local.com
  extraEnvs:
    - name: API_BASE_PATH
      value: http://storefront-bff.dev.svc.cluster.local/api
    - name: HOSTNAME
      value: "0.0.0.0"
  resources:
    requests:
      cpu: 10m
      memory: 128Mi