name: Test self-hosted runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, instance-20260511-133510]

    steps:
      - name: Check runner
        run: |
          hostname
          whoami
          pwd
          kubectl get pods -A
          helm version